### ISSUE TITLE
Monitor error

### ISSUE THREAD

**Issue by antman1p** [GhostManager/DomainCheck#2]
When I try to run the monitor command I receive the following error (Checkup works as intended):
python domaincheck.py monitor -d mydomain1.com,mydomain2.com -i 60 --slack

Traceback (most recent call last):
  File "domaincheck.py", line 114, in <module>
    domaincheck()
  File "/root/.local/share/virtualenvs/DomainCheck-dPG1qyAL/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/share/virtualenvs/DomainCheck-dPG1qyAL/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/share/virtualenvs/DomainCheck-dPG1qyAL/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/share/virtualenvs/DomainCheck-dPG1qyAL/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/share/virtualenvs/DomainCheck-dPG1qyAL/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/share/virtualenvs/DomainCheck-dPG1qyAL/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: monitor() got an unexpected keyword argument 'domains'

**Comment by chrismaddalena** [comment]
Sorry this took me so long to address with the holidays and a busy start to the new year :)

This was just a dumb mistake. The `checkup` mode has a `--filter-list` option. That argument makes sense for checkup, but I thought a `--domains` argument fit better for `monitor` mode, since you aren't really filtering anything so much as naming the domains you want to monitor. I forgot to update the CLICK function with the new name and in CLICK the argument names are the only thing that matters. Oops 👎 Super simple to fix.

This is resolved in the latest commit.
